vuu.certPath="./certs/cert.pem"
vuu.keyPath="./certs/key.pem"
vuu.ssl=true
vuu.websocket.port=8093
vuu.https.port=8445
vuu.keycloak.url="https://localhost:8080"
vuu.keycloak.realm="vuu"
vuu.keycloak.allowSelfSignedCert=true
vuu.auth.cors.allowedOrigin="http://localhost:5002"
vuu.auth.path="/api/authn"
vuu.auth.keycloak.clientId="vuu-basket-trading-server"
vuu.auth.keycloak.clientSecret="MUmAPGyQlCtDV7wBALziXw2Ai1kOpwLj"
vuu.auth.keycloak.audience="vuu-basket-trading-server"
vuu.auth.keycloak.audiencePolicy="require-audience"
vuu.auth.keycloak.tokenExchangeEnabled=false
