service.port=8083
services.refdata.url="ws://localhost:8081"
# parent orders created once instruments are loaded
orders.initialCount=10000
# new orders generated per second on startup, 0 = don't start
orders.newOrdersPerSecond=0
