/**
 * RIC suffix and Bloomberg exchange code by operating MIC. RICs here follow
 * the public ticker + exchange suffix convention, they are not sourced from
 * LSEG.
 */
export const EXCHANGES: Record<string, { bbg?: string; ric: string }> = {
  XAMS: { bbg: "NA", ric: ".AS" },
  XATH: { bbg: "GA", ric: ".AT" },
  XBER: { bbg: "GB", ric: ".BE" },
  XBRU: { bbg: "BB", ric: ".BR" },
  XBSE: { bbg: "RE", ric: ".RO" },
  XBUD: { bbg: "HB", ric: ".BU" },
  XBUL: { bbg: "BU", ric: ".BB" },
  XCSE: { bbg: "DC", ric: ".CO" },
  XCYS: { bbg: "CY", ric: ".CY" },
  XDUB: { bbg: "ID", ric: ".I" },
  XDUS: { bbg: "GD", ric: ".D" },
  XETR: { bbg: "GY", ric: ".DE" },
  XFRA: { bbg: "GF", ric: ".F" },
  XHAM: { bbg: "GH", ric: ".HM" },
  XHAN: { bbg: "GI", ric: ".HA" },
  XHEL: { bbg: "FH", ric: ".HE" },
  XICE: { bbg: "IR", ric: ".IC" },
  XLIS: { bbg: "PL", ric: ".LS" },
  XLIT: { bbg: "LH", ric: ".VL" },
  XLJU: { bbg: "SV", ric: ".LJ" },
  XLUX: { bbg: "LX", ric: ".LU" },
  XMAD: { bbg: "SQ", ric: ".MC" },
  XMAL: { bbg: "MV", ric: ".MT" },
  XMIL: { bbg: "IM", ric: ".MI" },
  XMSM: { bbg: "ID", ric: ".I" },
  XMUN: { bbg: "GM", ric: ".MU" },
  XOSL: { bbg: "NO", ric: ".OL" },
  XPAR: { bbg: "FP", ric: ".PA" },
  XPRA: { bbg: "CK", ric: ".PR" },
  XRIS: { bbg: "LR", ric: ".RI" },
  XSTO: { bbg: "SS", ric: ".ST" },
  XSTU: { bbg: "GS", ric: ".SG" },
  XTAL: { bbg: "ET", ric: ".TL" },
  XWAR: { bbg: "PW", ric: ".WA" },
  XWBO: { bbg: "AV", ric: ".VI" },
  XZAG: { bbg: "ZA", ric: ".ZA" },
};

/** Main exchange by country, for venues (e.g. MTFs) without a RIC suffix. */
export const COUNTRY_EXCHANGE: Record<string, string> = {
  AT: "XWBO",
  BE: "XBRU",
  BG: "XBUL",
  CY: "XCYS",
  CZ: "XPRA",
  DE: "XETR",
  DK: "XCSE",
  EE: "XTAL",
  ES: "XMAD",
  FI: "XHEL",
  FR: "XPAR",
  GR: "XATH",
  HR: "XZAG",
  HU: "XBUD",
  IE: "XMSM",
  IS: "XICE",
  IT: "XMIL",
  LT: "XLIT",
  LU: "XLUX",
  LV: "XRIS",
  MT: "XMAL",
  NL: "XAMS",
  NO: "XOSL",
  PL: "XWAR",
  PT: "XLIS",
  RO: "XBSE",
  SE: "XSTO",
  SI: "XLJU",
};
