vuu.certPath="./certs/cert.pem"
vuu.keyPath="./certs/key.pem"
vuu.ssl=true
vuu.websocket.port=8091
services.refdata.url="ws://localhost:8081"
services.prices.url="ws://localhost:8082"
services.orders.url="ws://localhost:8083"

vuu.https.port=8443
vuu.auth.mode="permissive"
vuu.auth.permissive.users=""
vuu.auth.path="/api/authn"