import { TableSchema } from "@vuu-ui/vuu-data-types";

export const instrumentsSchema: TableSchema = {
  columns: [
    { name: "bbg", serverDataType: "string" },
    { name: "currency", serverDataType: "string" },
    { name: "description", serverDataType: "string" },
    { name: "exchange", serverDataType: "string" },
    { name: "isin", serverDataType: "string" },
    { name: "lotSize", serverDataType: "int" },
    { name: "ric", serverDataType: "string" },
  ],
  key: "ric",
  table: {
    module: "ORDERS",
    table: "instruments",
  },
};

export const parentOrdersSchema: TableSchema = {
  columns: [
    { name: "id", serverDataType: "string" },
    { name: "side", serverDataType: "string" },
    { name: "status", serverDataType: "string" },
    { name: "ric", serverDataType: "string" },
    { name: "algo", serverDataType: "string" },
    { name: "ccy", serverDataType: "string" },
    { name: "quantity", serverDataType: "double" },
    { name: "filledQuantity", serverDataType: "double" },
    { name: "account", serverDataType: "string" },
    { name: "trader", serverDataType: "string" },
    { name: "created", serverDataType: "long" },
    { name: "lastUpdate", serverDataType: "long" },
    { name: "column13", serverDataType: "double" },
    { name: "column14", serverDataType: "double" },
    { name: "column15", serverDataType: "double" },
    { name: "column16", serverDataType: "double" },
    { name: "column17", serverDataType: "double" },
    { name: "column18", serverDataType: "double" },
    { name: "column19", serverDataType: "double" },
    { name: "column20", serverDataType: "double" },
    { name: "column21", serverDataType: "double" },
    { name: "column22", serverDataType: "double" },
    { name: "column23", serverDataType: "double" },
    { name: "column24", serverDataType: "double" },
    { name: "column25", serverDataType: "double" },
    { name: "column26", serverDataType: "double" },
    { name: "column27", serverDataType: "double" },
    { name: "column28", serverDataType: "double" },
    { name: "column29", serverDataType: "double" },
    { name: "column30", serverDataType: "double" },
    { name: "column31", serverDataType: "double" },
    { name: "column32", serverDataType: "double" },
    { name: "column33", serverDataType: "double" },
    { name: "column34", serverDataType: "double" },
    { name: "column35", serverDataType: "double" },
    { name: "column36", serverDataType: "double" },
    { name: "column37", serverDataType: "double" },
    { name: "column38", serverDataType: "double" },
    { name: "column39", serverDataType: "double" },
    { name: "column40", serverDataType: "double" },
  ],
  key: "id",
  table: {
    module: "ORDERS",
    table: "parentOrders",
  },
};
